package com.fitlife.ai.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4A6741)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCCEFBD)
val md_theme_light_onPrimaryContainer = Color(0xFF082100)
val md_theme_light_secondary = Color(0xFF54634D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7E8CC)
val md_theme_light_onSecondaryContainer = Color(0xFF121F0E)
val md_theme_light_tertiary = Color(0xFF3A656E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF8FBF1)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFF8FBF1)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFFB0D3A3)
val md_theme_dark_onPrimary = Color(0xFF1D370F)
val md_theme_dark_primaryContainer = Color(0xFF334F2A)
val md_theme_dark_onPrimaryContainer = Color(0xFFCCEFBD)
val md_theme_dark_secondary = Color(0xFFBCCBB1)
val md_theme_dark_onSecondary = Color(0xFF273422)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE2E3DB)
val md_theme_dark_surface = Color(0xFF1A1C18)
val md_theme_dark_onSurface = Color(0xFFE2E3DB)
