package com.fitlife.ai.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF15803D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDCFCE7)
val md_theme_light_onPrimaryContainer = Color(0xFF052E16)
val md_theme_light_secondary = Color(0xFF2563EB)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDBEAFE)
val md_theme_light_onSecondaryContainer = Color(0xFF172554)
val md_theme_light_tertiary = Color(0xFFEA580C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF8FAF9)
val md_theme_light_onBackground = Color(0xFF0F172A)
val md_theme_light_surface = Color(0xFFF8FAF9)
val md_theme_light_onSurface = Color(0xFF0F172A)
val md_theme_light_surfaceVariant = Color(0xFFE2E8F0)
val md_theme_light_onSurfaceVariant = Color(0xFF475569)
val md_theme_light_outline = Color(0xFF94A3B8)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_onError = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFF4ADE80)
val md_theme_dark_onPrimary = Color(0xFF052E16)
val md_theme_dark_primaryContainer = Color(0xFF14532D)
val md_theme_dark_onPrimaryContainer = Color(0xFFBBF7D0)
val md_theme_dark_secondary = Color(0xFF60A5FA)
val md_theme_dark_onSecondary = Color(0xFF172554)
val md_theme_dark_secondaryContainer = Color(0xFF1E3A8A)
val md_theme_dark_onSecondaryContainer = Color(0xFFDBEAFE)
val md_theme_dark_tertiary = Color(0xFFFB923C)
val md_theme_dark_onTertiary = Color(0xFF431407)
val md_theme_dark_background = Color(0xFF0B0F0D)
val md_theme_dark_onBackground = Color(0xFFE2E8F0)
val md_theme_dark_surface = Color(0xFF101512)
val md_theme_dark_onSurface = Color(0xFFE2E8F0)
val md_theme_dark_surfaceVariant = Color(0xFF1E293B)
val md_theme_dark_onSurfaceVariant = Color(0xFF94A3B8)
val md_theme_dark_outline = Color(0xFF475569)
val md_theme_dark_error = Color(0xFFF87171)
val md_theme_dark_onError = Color(0xFF450A0A)

val HeroGradientStart = Color(0xFF22C55E)
val HeroGradientEnd = Color(0xFF0D9488)
val AccentOrange = Color(0xFFF97316)
val AccentBlue = Color(0xFF3B82F6)
val AccentPurple = Color(0xFF8B5CF6)
